resolver: lts-7.1

packages:
- '.'

extra-deps:
  - text-regex-replace-0.1.1.1

flags: {}

extra-package-dbs: []

# Needed on OS X
extra-include-dirs:
  - /usr/local/Cellar/icu4c/57.1/include
extra-lib-dirs:
  - /usr/local/Cellar/icu4c/57.1/lib
